services:
  academichistoryms:
    build: ../AcademicHistory
    container_name: academichistoryms
    expose:
      - 8000
    ports:
      - 8001:8000
  calificationsms:
    build: ../califications
    container_name: calificationsms
    expose:
      - 8000
    ports:
      - 8002:8000

  courses_db:
    build: ../courses/courses_ms/courses_db
    container_name: courses_db
    environment:
      - MYSQL_DATABASE=courses_db
      - MYSQL_PASSWORD=2022
      - MYSQL_ROOT_PASSWORD=2022
      - MYSQL_USER=courses
    ports:
      - 3306:3306
    volumes:
      - courses_db:/var/lib/mysql

  coursesms:
    container_name: coursesms
    build: ../courses/courses_ms
    depends_on:
      - courses_db
    expose:
      - 8000
    ports:
      - 8080:8080

  enrollsms:
    build: ../EnrollsAPI
    container_name: enrollsms
    expose:
      - 8080
    ports:
      - 8003:8080

  schedulems:
    build: ../schedule
    container_name: schedulems
    expose:
      - 8000
    ports:
      - 8004:8000
        
  user_infoms:
    build: ../userInfo
    container_name: user_infoms
    depends_on:
      - user_information_db
      - rabbitmq
    environment:
      - MYSQL_DB=USER_INFORMATION
      - MYSQL_USER=grupo1b
      - MYSQL_PASSWORD=cristianoronaldo
      - MYSQL_HOST=user_information_db
      - MYSQL_PORT=3306
      - MQHOST=rabbitmq
      - MQPORT=5672
    expose:
      - 3000
    ports:
      - 3000:3000

  user_information_db:
    build: ../userInfo/user_information_db
    command: --default-authentication-plugin=mysql_native_password
    container_name: user_information_db
    environment:
      - MYSQL_ROOT_PASSWORD=contrasenasegura
      - MYSQL_DATABASE=USER_INFORMATION
      - MYSQL_USER=grupo1b
      - MYSQL_PASSWORD=cristianoronaldo
    expose:
      - 3306
    ports:
      - 3305:3306
    volumes:
      - user_information_db:/var/lib/mysql
  api_gateway:
    build: ../ApiGateway
    container_name: api_gateway
    depends_on:
      - user_information_db
      - schedulems
      - calificationsms
      - enrollsms
      - coursesms
      - academichistoryms
      - rabbitmq
    environment:
      - COURSES_ROUTE=coursesms
      - COURSES_PORT=8080
      - USERS_ROUTE=user_infoms
      - USERS_PORT=3000
      - SCHEDULES_ROUTE=schedulems
      - SCHEDULES_PORT=8000
      - CALIFICATIONS_ROUTE=calificationsms
      - CALIFICATIONS_PORT=8000
      - ACADEMICHISTORY_ROUTE=academichistoryms
      - ACADEMICHISTORY_PORT=8000
      - ENROLLS_ROUTE=enrollsms
      - ENROLLS_PORT=8080
      - MQHOST=rabbitmq
      - MQPORT=5672
    expose:
      - 4000
    ports:
      - 4000:4000
  frontweb:
     build: ../frontweb
     container_name: front_web
     expose: 
       - 3000
     ports:
       - 3001:3000
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10-management
    ports:
      - 5672:5672

version: "3.8"
volumes:
  courses_db:
  user_information_db:
