services:
  academic_history_ms:
    build: ../AcademicHistory
    container_name: academic_history_ms
    expose:
      - 8001
    ports:
      - 8001:8000
  califications_ms:
    build: ../califications
    container_name: califications_ms
    expose:
      - 8002
    ports:
      - 8002:8000

  courses_db:
    build: ../courses/courses_ms/courses_db
    container_name: courses_db
    environment:
      - MYSQL_DATABASE=courses_db
      - MYSQL_PASSWORD=2022
      - MYSQL_ROOT_PASSWORD=2022
      - MYSQL_USER=courses
    ports:
      - 3306:3306
    volumes:
      - courses_db:/var/lib/mysql

  courses_ms:
    container_name: courses_ms
    build: ../courses/courses_ms
    depends_on:
      - courses_db
    ports:
      - 8080:8080

  enrolls_ms:
    build: ../EnrollsAPI
    container_name: enrolls_ms
    ports:
      - 8003:8080

  schedule_ms:
    build: ../schedule
    container_name: schedule_ms
    ports:
      - 8004:8000
        
  user_info_ms:
    build: ../userInfo
    container_name: user_info_ms
    depends_on:
      - user_information_db
      - rabbitmq
    environment:
      - MYSQL_DB=USER_INFORMATION
      - MYSQL_USER=grupo1b
      - MYSQL_PASSWORD=cristianoronaldo
      - MYSQL_HOST=user_information_db
      - MYSQL_PORT=3306
      - MQHOST=rabbitmq
      - MQPORT=5672
    expose:
      - 3000
    ports:
      - 3000:3000

  user_information_db:
    build: ../userInfo/user_information_db
    command: --default-authentication-plugin=mysql_native_password
    container_name: user_information_db
    environment:
      - MYSQL_ROOT_PASSWORD=contrasenasegura
      - MYSQL_DATABASE=USER_INFORMATION
      - MYSQL_USER=grupo1b
      - MYSQL_PASSWORD=cristianoronaldo
    expose:
      - 3306
    ports:
      - 3305:3306
    volumes:
      - user_information_db:/var/lib/mysql
  api_gateway:
    build: .../ApiGateway
    container_name: api_gateway
    depends_on:
      - user_information_db
      - schedule_ms
      - califications_ms
      - enrolls_ms
      - courses_ms
      - academic_history_ms
      - rabbitmq
    expose:
      - 4000
    ports:
      - 4000:4000
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10-management
    ports:
      - 5672:5672

version: "3.8"
volumes:
  courses_db:
  user_information_db:
